name: Feature Request
description: Create a feature request for Vencord. To request new plugins, please use the Discussions tab
labels: [enhancement]

body:
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Who on Discord is making this request? Not required but encouraged for easier follow-up
      placeholder: username#0000
    validations:
      required: false

  - type: textarea
    id: feature-basic-description
    attributes:
      label: What is it that you'd like to see?
      description: Describe the feature you want added as detailed as possible
      placeholder: I think ... would be a cool feature to add. This would be awesome, thanks!
    validations:
      required: true
